services:
  server:
    build:
      context: .
    ports:
      - 8007:80
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - secrets-data:/code/secrets
      - app-data:/code/app-data
    environment:
      - APP_URL=${APP_URL:-} 
      - API_KEYS_PATH=${API_KEYS_PATH:-/code/secrets/apikeys.json}
      - HTTPS_ONLY=${HTTPS_ONLY:-true}
      - LOCAL_DATA_PATH=${LOCAL_DATA_PATH:-/code/app-data/}
      - ROUTER_IP=${ROUTER_IP:-192.168.8.1}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - VAPID_CLAIM_SUBJECT=${VAPID_CLAIM_SUBJECT:-}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
      - SHOW_ADMIN_AUTH=${SHOW_ADMIN_AUTH:-false}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY:-}
      - WEATHER_LAT=${WEATHER_LAT:-}
      - WEATHER_LON=${WEATHER_LON:-}
      - WEATHER_CACHE_TTL_SECONDS=${WEATHER_CACHE_TTL_SECONDS:-}
      - PRESENCE_POLLING_INTERVAL_SECONDS=${PRESENCE_POLLING_INTERVAL_SECONDS:-}
      - PRESENCE_POLLING_DELAY_SECONDS=${PRESENCE_POLLING_DELAY_SECONDS:-}
      - INTERNAL_POLLING_INTERVAL_SECONDS=${INTERNAL_POLLING_INTERVAL_SECONDS:-}
      - INTERNAL_POLLING_DELAY_SECONDS=${INTERNAL_POLLING_DELAY_SECONDS:-}
      - OCCUPANCY_POLLING_INTERVAL_SECONDS=${OCCUPANCY_POLLING_INTERVAL_SECONDS:-}
      - CSP_DOMAIN=${CSP_DOMAIN:-}
      - OPERATOR_NAME=${OPERATOR_NAME:-}
      - OPERATOR_EMAIL=${OPERATOR_EMAIL:-}
    restart: unless-stopped

volumes:
  secrets-data:
  app-data: