services:
  server:
    build:
      context: .
    ports:
      - 8007:80
    volumes:
      - secrets-data:/code/secrets
      - app-data:/code/app-data
    environment:
      - API_KEYS_PATH=${API_KEYS_PATH:-/code/secrets/apikeys.json}
      - HTTPS_ONLY=${HTTPS_ONLY:-true}
      - INTERNAL_POLLING_DELAY_SECONDS=${INTERNAL_POLLING_DELAY_SECONDS:-30}
      - INTERNAL_POLLING_INTERVAL_SECONDS=${INTERNAL_POLLING_INTERVAL_SECONDS:-60}
      - LOCAL_DATA_PATH=${LOCAL_DATA_PATH:-/code/app-data/}
      - OCCUPANCY_POLLING_INTERVAL_SECONDS=${OCCUPANCY_POLLING_INTERVAL_SECONDS:-360}
      - PRESENCE_POLLING_DELAY_SECONDS=${PRESENCE_POLLING_DELAY_SECONDS:-0}
      - PRESENCE_POLLING_INTERVAL_SECONDS=${PRESENCE_POLLING_INTERVAL_SECONDS:-60}
      - ROUTER_IP=${ROUTER_IP:-192.168.8.1}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - VAPID_CLAIM_SUBJECT=${VAPID_CLAIM_SUBJECT:-}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
      - SHOW_ADMIN_AUTH=${SHOW_ADMIN_AUTH:-false}
    restart: unless-stopped

volumes:
  secrets-data:
  app-data: