# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8007:80
    environment:
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - ROUTER_IP=${ROUTER_IP:-192.168.8.1}
      - WEEKLY_PLAN_URL=${WEEKLY_PLAN_URL}
      - EVENT_CALENDAR_URL=${EVENT_CALENDAR_URL}
    restart: unless-stopped